services:
  # Next.js 应用
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env.test
    ports:
      - '3000:3000'
    depends_on:
      - db  # 简化依赖关系
    networks:
      - qiushui-network

  # PostgreSQL 数据库
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=qiushui_blog
      - PGDATA=/var/lib/postgresql/data/pgdata  # 明确指定PGDATA路径
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]  # 启用详细日志记录
    networks:
      - qiushui-network

networks:
  qiushui-network:
    driver: bridge

volumes:
  postgres_data:
    name: qiushui_blog_postgres_data
 